# Generated by Django 5.2.7 on 2025-10-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_legal', models.CharField(max_length=200, verbose_name='Nombre legal')),
                ('apellidos', models.CharField(blank=True, max_length=200, verbose_name='Apellidos')),
                ('rut', models.CharField(max_length=30, verbose_name='RUT')),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=50, verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección/Domicilio')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo institucional')),
                ('campus', models.CharField(blank=True, max_length=100, verbose_name='Campus/Sede')),
                ('nombre_social', models.CharField(blank=True, max_length=200, verbose_name='Nombre social')),
                ('rol', models.CharField(max_length=50, verbose_name='Rol')),
                ('firma', models.BooleanField(default=False, verbose_name='Acepta y firma (checkbox)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_pdfs/', verbose_name='PDF generado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
